"""Simulation via Icarus Verilog, on the synthesized gate-level netlist.

Every problem gets two generated testbenches over the same netlist:

  score     every input port streams its beats back-to-back, `out_ready` is
            held high. This is the timing measurement: cycles from the first
            accepted input to the last accepted output, summed over the
            back-to-back transactions, with no testbench-imposed idle cycles.

  protocol  seeded input gaps on every port and seeded output backpressure,
            plus a conformance check that fails the run if the DUT drops or
            changes an output while `out_ready` is low. Results must still
            match the golden model; cycles are ignored.

Each input port has its own valid/ready handshake and its own length, so
matrix problems can stream operands of different sizes independently. The
testbench drives `transactions` back-to-back transactions without resetting;
the DUT must clear any per-transaction state when it emits the last output
word.

The simulated artifact is `netlist.v`, written by the pinned yosys flow after
elaboration at the problem's parameters.

The testbench is assembled from the Verilog snippets below. Each snippet is a
function of the port name (and a few settings), so the generated Verilog is
visible here more or less as it will appear in `tb_<mode>.v`.
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
from functools import lru_cache
from pathlib import Path
from shutil import which

from .problem import Problem
from .process import run_logged

MODES = ("score", "protocol")
MAX_CYCLES = 200_000
RESULT_LINE = re.compile(r"RESULT (\w+) CYCLES (\d+)")


# --------------------------------------------------------------------------
# Testbench generation
# --------------------------------------------------------------------------


def render_tb(problem: Problem, seed: int | str = 0, mode: str = "score") -> str:
    """The Verilog testbench for one case in one mode."""
    if mode not in MODES:
        raise ValueError(f"unknown testbench mode {mode!r}")

    protocol = mode == "protocol"
    lanes = int(problem.params["LANES"])
    ports = problem.input_ports
    lengths = problem.input_lens
    for port in ports:
        if lengths[port] % lanes != 0:
            raise ValueError(
                f"{problem.name}: port {port} length {lengths[port]} "
                f"is not a multiple of LANES={lanes}"
            )

    port_params = "\n".join(_port_params(port, lengths[port]) for port in ports)
    port_declarations = "\n".join(_port_declarations(port) for port in ports)
    port_connections = "\n".join(_port_connections(port) for port in ports)
    port_drivers = "\n".join(
        _port_driver(port, lengths[port], lengths[port] // lanes, protocol) for port in ports
    )
    input_count_checks = "\n".join(_input_count_check(port) for port in ports)
    readmem = "\n".join(f'    $readmemh("{port}_beats.hex", {port}_mem);' for port in ports)

    if protocol:
        base_seed = _case_seed(seed)
        port_lfsrs = "\n".join(
            _port_lfsr(port, _lfsr_literal(base_seed + 101 * (index + 1)))
            for index, port in enumerate(ports)
        )
        out_ready_driver = _out_ready_driver(_lfsr_literal(base_seed))
        protocol_check = PROTOCOL_CHECK
        out_ready_initial = "1'b0"
    else:
        port_lfsrs = ""
        out_ready_driver = ""
        protocol_check = ""
        out_ready_initial = "1'b1"

    return f"""\
`timescale 1ns / 1ps
// Generated by ADPBench. Do not edit.
// Mode: {mode}
module tb;
  parameter LANES      = {lanes};
  parameter DATA_W     = {problem.params["DATA_W"]};
  parameter ACC_W      = {problem.params["ACC_W"]};
  parameter OUT_LEN    = {problem.out_len};
  parameter TXNS       = {problem.transactions};
  parameter MAX_CYCLES = {MAX_CYCLES};
{port_params}

  reg clk = 1'b0;
  always #5 clk = ~clk;          // 100 MHz

  reg rst_n = 1'b0;
  reg txn_go = 1'b0;
  reg txn_active = 1'b0;
  integer txn = 0;

{port_declarations}
  wire out_valid;
  reg  out_ready = {out_ready_initial};
  wire [ACC_W-1:0] out_c;

  reg [ACC_W-1:0] out_words [0:TXNS*OUT_LEN-1];

  {problem.top} u_dut (
    .clk(clk),
    .rst_n(rst_n),
{port_connections}
    .out_valid(out_valid),
    .out_ready(out_ready),
    .out_c(out_c)
  );

  reg protocol_error = 1'b0;
{port_lfsrs}
{port_drivers}
{out_ready_driver}
{protocol_check}
  integer out_count   = 0;
  integer total_words = 0;
  reg     txn_done    = 1'b0;
  reg     timed_out   = 1'b0;
  reg     counting    = 1'b0;
  reg     done        = 1'b0;
  integer cycle_count  = 0;
  integer total_cycles = 0;

  always @(posedge clk) begin
    if (!rst_n) begin
      out_count    <= 0;
      total_words  <= 0;
      txn_done     <= 1'b0;
      timed_out    <= 1'b0;
      counting     <= 1'b0;
      cycle_count  <= 0;
      total_cycles <= 0;
    end else begin
      if (txn_go) txn_done <= 1'b0;
      // Time is measured from when the transaction's inputs are first
      // presented, not from the first handshake, so a DUT cannot compute
      // before acknowledging for free.
      if (txn_active) counting <= 1'b1;
      if (counting) cycle_count <= cycle_count + 1;
      // Only outputs produced while a transaction is active count; a DUT that
      // presents stale data between transactions must not be credited for it.
      if (txn_active && out_valid && out_ready && total_words < TXNS*OUT_LEN) begin
        out_words[total_words] <= out_c;
        total_words <= total_words + 1;
        if (out_count + 1 == OUT_LEN) begin
          total_cycles <= total_cycles + cycle_count + 1;
          cycle_count  <= 0;
          counting     <= 1'b0;
          out_count    <= 0;
          txn_done     <= 1'b1;
{input_count_checks}
        end else begin
          out_count <= out_count + 1;
        end
      end else if (total_words >= TXNS*OUT_LEN && out_valid && out_ready) begin
        // More accepted output words than the task defines.
        protocol_error <= 1'b1;
      end
      if (total_cycles + cycle_count > MAX_CYCLES) timed_out <= 1'b1;
    end
  end

  integer t;
  initial begin
{readmem}
    repeat (4) @(posedge clk);
    @(negedge clk);
    rst_n = 1'b1;

    for (t = 0; t < TXNS; t = t + 1) begin
      @(negedge clk);
      txn        = t;
      txn_active = 1'b1;
      txn_go     = 1'b1;
      @(negedge clk);
      txn_go     = 1'b0;
      wait (txn_done || timed_out);
      txn_active = 1'b0;
      if (timed_out) begin
        if (protocol_error)
          $display("RESULT PROTOCOL CYCLES %0d", total_cycles + cycle_count);
        else
          $display("RESULT TIMEOUT CYCLES %0d", total_cycles + cycle_count);
        $finish;
      end
    end

    if (protocol_error) begin
      $display("RESULT PROTOCOL CYCLES %0d", total_cycles);
    end else begin
      $writememh("out_{mode}.hex", out_words);
      $display("RESULT OK CYCLES %0d", total_cycles);
    end
    $finish;
  end
endmodule
"""


def _upper_name(port: str) -> str:
    """A port name as a Verilog localparam prefix, e.g. `a` -> `A`."""
    return re.sub(r"\W", "_", port).upper()


def _port_params(port: str, length: int) -> str:
    prefix = _upper_name(port)
    return f"  localparam {prefix}_LEN   = {length};\n  localparam {prefix}_BEATS = {prefix}_LEN / LANES;"


def _port_declarations(port: str) -> str:
    """The stimulus memory and handshake signals for one input port."""
    prefix = _upper_name(port)
    return f"""\
  wire [LANES*DATA_W-1:0] {port};
  reg                     {port}_valid = 1'b0;
  wire                    {port}_ready;
  reg  [LANES*DATA_W-1:0] {port}_mem [0:TXNS*{prefix}_BEATS-1];
  integer                 {port}_idx = 0;
  integer                 {port}_count = 0;
  assign {port} = {port}_mem[txn*{prefix}_BEATS + {port}_idx];"""


def _port_connections(port: str) -> str:
    return (
        f"    .{port}({port}),\n"
        f"    .{port}_valid({port}_valid),\n"
        f"    .{port}_ready({port}_ready),"
    )


def _port_driver(port: str, length: int, beats: int, protocol: bool) -> str:
    """Drives one input port's beats for each transaction.

    In the score run, `valid` stays high between beats. In the protocol run,
    `valid` drops after every accepted beat for a seeded 1-4 cycle gap.
    """
    prefix = _upper_name(port)
    valid_after_beat = "1'b0" if protocol else "1'b1"
    gap_after_beat = f"3'd1 + {port}_lfsr[1:0]" if protocol else "3'd0"
    return f"""\
  // Port `{port}`: {length} elements per transaction, {beats} beats.
  integer  {port}_beat = 0;
  reg      {port}_active = 1'b0;
  reg [2:0] {port}_gap = 3'd0;
  always @(posedge clk) begin
    if (!rst_n) begin
      {port}_valid  <= 1'b0;
      {port}_active <= 1'b0;
      {port}_beat   <= 0;
      {port}_idx    <= 0;
      {port}_count  <= 0;
      {port}_gap    <= 3'd0;
    end else if (txn_go) begin
      {port}_valid  <= 1'b1;
      {port}_active <= 1'b1;
      {port}_beat   <= 0;
      {port}_idx    <= 0;
      {port}_count  <= 0;
      {port}_gap    <= 3'd0;
    end else if ({port}_active) begin
      if ({port}_valid) begin
        if ({port}_ready) begin
          {port}_count <= {port}_count + 1;
          if ({port}_beat == {prefix}_BEATS - 1) begin
            {port}_valid  <= 1'b0;
            {port}_active <= 1'b0;
          end else begin
            {port}_beat <= {port}_beat + 1;
            {port}_idx  <= {port}_idx + 1;
            {port}_valid <= {valid_after_beat};
            {port}_gap   <= {gap_after_beat};
          end
        end
      end else if ({port}_gap != 3'd0) begin
        {port}_gap <= {port}_gap - 1;
      end else begin
        {port}_valid <= 1'b1;
      end
    end
  end"""


def _input_count_check(port: str) -> str:
    """On the last output word, every beat of this port must have been accepted."""
    prefix = _upper_name(port)
    return (
        f"          if (({port}_count + (({port}_valid && {port}_ready) ? 1 : 0)) != {prefix}_BEATS)\n"
        f"            protocol_error <= 1'b1;"
    )


def _port_lfsr(port: str, seed: str) -> str:
    """A 16-bit LFSR that picks the gap lengths for one input port."""
    return f"""\
  reg [15:0] {port}_lfsr = {seed};
  always @(posedge clk) begin
    if (!rst_n) {port}_lfsr <= {seed};
    else {port}_lfsr <= {{ {port}_lfsr[14:0], {port}_lfsr[15] ^ {port}_lfsr[13] ^ {port}_lfsr[12] ^ {port}_lfsr[10] }};
  end"""


def _out_ready_driver(seed: str) -> str:
    return f"""\
  // Deterministic hold-stability pressure: every presented output word is
  // held off for 1-4 seeded cycles before it can be accepted, and there is a
  // seeded low gap after each acceptance. A DUT that drops or mutates a word
  // while stalled is caught on its first word, not by luck.
  reg [15:0] out_lfsr = {seed};
  reg [2:0]  pressure_phase = 3'd0;
  reg [2:0]  pressure_count = 3'd0;
  always @(posedge clk) begin
    if (!rst_n) begin
      out_lfsr       <= {seed};
      out_ready      <= 1'b0;
      pressure_phase <= 3'd0;
      pressure_count <= 3'd0;
    end else begin
      out_lfsr <= {{ out_lfsr[14:0], out_lfsr[15] ^ out_lfsr[13] ^ out_lfsr[12] ^ out_lfsr[10] }};
      case (pressure_phase)
        3'd0: begin
          out_ready <= 1'b0;
          if (out_valid) begin
            pressure_count <= 3'd1 + out_lfsr[2:1];
            pressure_phase <= 3'd1;
          end
        end
        3'd1: begin
          out_ready <= 1'b0;
          if (pressure_count <= 3'd1) pressure_phase <= 3'd2;
          else pressure_count <= pressure_count - 3'd1;
        end
        default: begin
          out_ready      <= 1'b1;
          pressure_phase <= 3'd0;
        end
      endcase
      if (out_valid && out_ready) begin
        out_ready      <= 1'b0;
        pressure_phase <= 3'd0;
      end
    end
  end"""


PROTOCOL_CHECK = """\
  // Valid/ready conformance: while an output is presented and not accepted,
  // it must stay presented and unchanged.
  reg             out_stalled = 1'b0;
  reg [ACC_W-1:0] out_stalled_data = 0;
  always @(posedge clk) begin
    if (!rst_n) begin
      out_stalled      <= 1'b0;
      out_stalled_data <= 0;
      protocol_error   <= 1'b0;
    end else begin
      if (out_stalled && (!out_valid || out_c !== out_stalled_data))
        protocol_error <= 1'b1;
      if (out_valid && !out_ready) begin
        out_stalled      <= 1'b1;
        out_stalled_data <= out_c;
      end else begin
        out_stalled <= 1'b0;
      end
    end
  end"""


def _case_seed(case: int | str) -> int:
    """An integer seed for a case: the seed itself, or a hash of a directed-case name."""
    if isinstance(case, int):
        return case
    digest = hashlib.sha256(str(case).encode()).digest()
    return int.from_bytes(digest[:4], "big")


def _lfsr_literal(seed: int) -> str:
    """A nonzero 16-bit LFSR start value derived from `seed`, as a Verilog literal."""
    value = ((seed * 0x9E3779B1 + 0xACE1) & 0xFFFF) or 1
    return f"16'h{value:04x}"


# --------------------------------------------------------------------------
# Running the simulator
# --------------------------------------------------------------------------


@lru_cache(maxsize=1)
def simlib_path() -> Path:
    """Locate yosys's simulation models for its internal cell types.

    `synth -noabc` emits `$_AND_`, `$_DFF_*`, ... instances. simlib.v is the
    behavioural model of those cells, so the netlist can be simulated as-is.
    `ADPBENCH_SIMLIB` overrides the search.
    """
    override = os.environ.get("ADPBENCH_SIMLIB")
    if override and Path(override).is_file():
        return Path(override)

    candidates: list[Path] = []
    config = which("yosys-config")
    if config:
        try:
            proc = subprocess.run([config, "--datdir"], capture_output=True, text=True, timeout=30)
            if proc.returncode == 0 and proc.stdout.strip():
                candidates.append(Path(proc.stdout.strip()))
        except (OSError, subprocess.TimeoutExpired):
            pass

    binary = which("yosys")
    if binary:
        for parent in Path(binary).resolve().parents:
            candidates.append(parent / "share" / "yosys")
    candidates += [
        Path("/usr/share/yosys"),
        Path("/usr/local/share/yosys"),
        Path("/opt/homebrew/share/yosys"),
    ]

    seen: set[Path] = set()
    for base in candidates:
        if base in seen:
            continue
        seen.add(base)
        for relative in ("simlib.v", "techlibs/common/simlib.v", "simcells.v"):
            path = base / relative
            if path.is_file():
                return path
    raise RuntimeError("cannot locate yosys simlib.v; set ADPBENCH_SIMLIB to its path")


def simulate(
    problem: Problem,
    netlist: Path,
    workdir: Path,
    seed: int | str = 0,
    mode: str = "score",
    deadline_at: float | None = None,
) -> dict:
    """Compile the netlist against a generated testbench and run it.

    Returns {"compiled", "finished", "timed_out", "status", "cycles",
    "out_file", "log"}, plus "failure_kind" when a tool itself failed.
    `status` is what the testbench reported (OK, TIMEOUT, PROTOCOL), or
    NO RESULT, COMPILE, WALL_TIMEOUT, or TOOL_ERROR.
    """
    if mode not in MODES:
        raise ValueError(f"unknown testbench mode {mode!r}")

    workdir = Path(workdir).resolve()
    workdir.mkdir(parents=True, exist_ok=True)
    testbench = workdir / f"tb_{mode}.v"
    testbench.write_text(render_tb(problem, seed, mode))
    out_file = workdir / f"out_{mode}.hex"
    binary = f"sim_{mode}.vvp"

    compile_command = [
        "iverilog", "-g2012", "-s", "tb", "-o", binary,
        str(Path(netlist).resolve()), str(simlib_path()), testbench.name,
    ]
    build = run_logged(compile_command, workdir, f"iverilog_{mode}", deadline_at=deadline_at)
    if build["returncode"] != 0 or build["reason"]:
        return {
            "compiled": False,
            "finished": False,
            "timed_out": build["timed_out"],
            "status": "COMPILE",
            "cycles": -1,
            "out_file": out_file,
            "log": build["log"],
            "failure_kind": build["reason"],
        }

    run = run_logged(["vvp", binary], workdir, f"vvp_{mode}", deadline_at=deadline_at)
    if run["returncode"] != 0 or run["reason"]:
        return {
            "compiled": True,
            "finished": False,
            "timed_out": run["timed_out"],
            "status": "WALL_TIMEOUT" if run["timed_out"] else "TOOL_ERROR",
            "cycles": -1,
            "out_file": out_file,
            "log": run["log"],
            "failure_kind": run["reason"],
        }

    match = RESULT_LINE.search(run["log"])
    if match is None:
        return {
            "compiled": True,
            "finished": False,
            "timed_out": False,
            "status": "NO RESULT",
            "cycles": -1,
            "out_file": out_file,
            "log": run["log"],
        }

    status, cycles = match.group(1), int(match.group(2))
    return {
        "compiled": True,
        "finished": status == "OK",
        "timed_out": status == "TIMEOUT",
        "status": status,
        "cycles": cycles,
        "out_file": out_file,
        "log": run["log"],
    }


@lru_cache(maxsize=1)
def tool_version() -> str:
    """First line of `iverilog -V`, or "unknown"."""
    try:
        proc = subprocess.run(["iverilog", "-V"], capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.TimeoutExpired):
        return "unknown"
    lines = (proc.stdout + proc.stderr).strip().splitlines()
    return lines[0] if lines else "unknown"
